services:
  db:
    image: mysql
    container_name: db_certification
    restart: always
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: pma_certification
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    volumes:
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - dev

  www:
    build: php
    container_name: www_certification
    ports:
      - "8741:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev
  node:
        image: node:20 # Choisissez la version de Node.js souhaitée
        container_name: node_certification
        working_dir: /var/www/app
        user: "$USERID"
        volumes:
            - .:/var/www/app
        tty: true

networks:
  dev:

volumes:
  database: